import js from '@eslint/js'
import tsParser from '@typescript-eslint/parser'
import tsPlugin from '@typescript-eslint/eslint-plugin'

// Root ESLint config — mirrors frontend/eslint.config.js but for the
// Cloudflare Worker runtime (Hono.js + workerd globals).
export default [
  {
    ignores: [
      'node_modules/**',
      'coverage/**',
      'worker-configuration.d.ts', // auto-generated by `wrangler types`
      'dist/**',
      'frontend/**', // frontend has its own config + deps
    ],
  },
  js.configs.recommended,
  {
    files: ['src/**/*.{ts,tsx}', 'test/**/*.ts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
      globals: {
        // workerd / Cloudflare Workers runtime
        caches: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        Headers: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        fetch: 'readonly',
        crypto: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        ReadableStream: 'readonly',
        TransformStream: 'readonly',
        WritableStream: 'readonly',
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        // @cloudflare/workers-types
        ExecutionContext: 'readonly',
        ScheduledEvent: 'readonly',
        D1Database: 'readonly',
        DurableObjectNamespace: 'readonly',
        DurableObjectStub: 'readonly',
        DurableObject: 'readonly',
        KVNamespace: 'readonly',
        Cache: 'readonly',
        CacheStorage: 'readonly',
        // vitest test runner
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeAll: 'readonly',
        beforeEach: 'readonly',
        afterAll: 'readonly',
        afterEach: 'readonly',
        vi: 'readonly',
        vitest: 'readonly',
        // cloudflare:test
        env: 'readonly',
        SELF: 'readonly',
        createExecutionContext: 'readonly',
        waitOnExecutionContext: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      ...tsPlugin.configs.recommended.rules,
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-undef': 'off',
      // Workers handlers commonly receive `c` as the first arg; allow it.
      'no-empty': ['error', { allowEmptyCatch: true }],
      // The codebase consistently uses literal type annotations instead of
      // `as const`; keep the warning so it surfaces but don't fail CI.
      '@typescript-eslint/prefer-as-const': 'warn',
    },
  },
  {
    // Test files: relax lint to match the project's existing test style —
    // fixtures frequently use `as any` for type assertions and shadow
    // helper imports with local functions. Tighten over time.
    files: ['test/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'no-redeclare': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
    },
  },
]
