name = "duckshort"
main = "src/index.tsx"
compatibility_date = "2024-04-15"
compatibility_flags = ["nodejs_compat"]

[dev]
port = 8787
local_protocol = "http"

[[d1_databases]]
binding = "DB"
database_name = "duckshort-db"
database_id = "cbb432e6-7252-461d-83ff-d792be1413fb"

[vars]
ADMIN_SECRET = "dev-secret"
BASE_URL = "http://localhost:8787"

[observability]
enabled = true
